#!/bin/bash
#
# tt-nginx-labs-apply.sh — augment the tertiarytraining nginx vhost with 10
# reverse-proxy locations for the Ubuntu / Kali Linux desktop demos, so they
# can be reached at https://www.tertiarytraining.com/lab/{ubuntu,kali}-N/.
#
# Idempotent: backs up the current vhost, regenerates it from scratch, runs
# `nginx -t` to validate, only reloads on success. n8n's evolution-ssl vhost
# is never touched.

set -uo pipefail

VHOST="/etc/nginx/sites-available/tertiarytraining"
BACKUP="${VHOST}.bak.$(date +%s)"

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root." >&2
  exit 1
fi

if [ ! -f "$VHOST" ]; then
  echo "$VHOST not found — has the initial nginx vhost been set up?" >&2
  exit 1
fi

# Read the CURRENT upstream IP from the existing vhost so the auto-sync
# timer's next run is a no-op rather than fighting us.
CURRENT_IP=$(grep -oE 'server 10\.0\.1\.[0-9]+:3000' "$VHOST" | head -1 | grep -oE '10\.0\.1\.[0-9]+')
if [ -z "$CURRENT_IP" ]; then
  CURRENT_IP="10.0.1.8"  # safe default; auto-sync timer corrects within 30s
  echo "  (note: couldn't read current upstream IP, using default $CURRENT_IP)"
fi

echo "=== Backing up $VHOST → $BACKUP ==="
cp -a "$VHOST" "$BACKUP"

echo "=== Writing new vhost ==="
cat > "$VHOST" <<'NGINX_EOF'
# Tertiary Training — host nginx reverse proxy
# Generated by tt-nginx-labs-apply.sh. Do not hand-edit the upstream line —
# tt-nginx-sync.timer rewrites it whenever the app container's IP changes.

upstream tertiary_app {
    server __APP_IP__:3000;
    keepalive 16;
}

# HTTP -> HTTPS (and ACME challenge passthrough)
server {
    listen 80;
    listen [::]:80;
    server_name www.tertiarytraining.com tertiarytraining.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    location / {
        return 301 https://www.tertiarytraining.com$request_uri;
    }
}

# Apex -> www on HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name tertiarytraining.com;

    ssl_certificate     /etc/letsencrypt/live/www.tertiarytraining.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.tertiarytraining.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    return 301 https://www.tertiarytraining.com$request_uri;
}

# Main HTTPS vhost
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.tertiarytraining.com;

    ssl_certificate     /etc/letsencrypt/live/www.tertiarytraining.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.tertiarytraining.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 50M;

    # ───── Lab desktops (Ubuntu + Kali via linuxserver/webtop + kali-linux) ─────
    # WebSocket-upgrading reverse proxies. SUBFOLDER on the container is set
    # to the matching path so Selkies generates correct asset URLs.

    # Ubuntu demos: host 8091..8095 -> /lab/ubuntu-1/ .. ubuntu-5/ (local engine)
    location /lab/ubuntu-1/ { proxy_pass http://127.0.0.1:8091; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/ubuntu-2/ { proxy_pass http://127.0.0.1:8092; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/ubuntu-3/ { proxy_pass http://127.0.0.1:8093; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/ubuntu-4/ { proxy_pass http://127.0.0.1:8094; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/ubuntu-5/ { proxy_pass http://127.0.0.1:8095; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }


    # Kali demos: host 8096..8100 -> /lab/kali-1/ .. kali-5/
    location /lab/kali-1/ { proxy_pass http://127.0.0.1:8096; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/kali-2/ { proxy_pass http://127.0.0.1:8097; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/kali-3/ { proxy_pass http://127.0.0.1:8098; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/kali-4/ { proxy_pass http://127.0.0.1:8099; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }
    location /lab/kali-5/ { proxy_pass http://127.0.0.1:8100; include /etc/nginx/snippets/tertiary-lab-proxy.conf; }

    # ───── Main Next.js app ─────
    location / {
        proxy_pass         http://tertiary_app;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
NGINX_EOF

# Replace the placeholder with the actual current IP
sed -i "s|__APP_IP__|$CURRENT_IP|" "$VHOST"

echo "=== Writing shared lab-proxy snippet ==="
mkdir -p /etc/nginx/snippets
cat > /etc/nginx/snippets/tertiary-lab-proxy.conf <<'SNIPPET_EOF'
# Shared proxy settings for /lab/* locations (Selkies/WebTop/Kali desktops).
# These streamers use WebSocket + WebRTC and need long-lived connections.
proxy_http_version 1.1;
proxy_set_header Host              $host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Upgrade           $http_upgrade;
proxy_set_header Connection        "upgrade";
proxy_buffering off;
proxy_read_timeout 86400s;
proxy_send_timeout 86400s;
proxy_connect_timeout 60s;
SNIPPET_EOF

echo "=== Validating nginx config ==="
if ! nginx -t 2>&1; then
  echo
  echo "✗ nginx -t failed. Rolling back from $BACKUP."
  cp -a "$BACKUP" "$VHOST"
  exit 1
fi

echo
echo "=== Reloading nginx ==="
systemctl reload nginx
echo "✓ nginx reloaded"

echo
echo "=== Verify (each should be 200 once the matching container is running) ==="
for i in 1 2 3 4 5; do
  CODE=$(curl -s -o /dev/null -m 5 -w "%{http_code}" -k https://www.tertiarytraining.com/lab/ubuntu-${i}/ || echo "TIMEOUT")
  echo "  ubuntu-${i}: $CODE"
done
for i in 1 2 3 4 5; do
  CODE=$(curl -s -o /dev/null -m 5 -w "%{http_code}" -k https://www.tertiarytraining.com/lab/kali-${i}/ || echo "TIMEOUT")
  echo "  kali-${i}:   $CODE"
done
echo
echo "Cards on https://www.tertiarytraining.com/dashboard now point at"
echo "  https://www.tertiarytraining.com/lab/ubuntu-N/"
echo "  https://www.tertiarytraining.com/lab/kali-N/"
echo "…valid TLS via the existing Let's Encrypt cert, no warnings."
